# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ROB / KuanYen Huang
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://12oi3.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "12OI3/12oi3.github.io"
twitter_username: "ROBsayYes"
github_username:  "12OI3"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# mmistakes syuff
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "default", "dirt", "neon", "mint", "plum", "sunrise"

author:
  name: &name ROB / KuanYen Huang
  avatar: /favicon.ico # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: >- 
    An average game programmer / designer / enjoyer.
  email: benbook90@gmail.com
  links:
    - label: Resume
      icon: fas fa-fw fa-user
      url: &resume /assets/resume.pdf" target="_blank
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: &twitterUrl https://x.com/ROBsayYes" target="_blank
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: &linkedinUrl https://www.linkedin.com/in/kuan-yen-huang-267079294/" target="_blank
    - label: Itch.io
      icon: fas fa-fw fa-gamepad
      url: &itch https://intoxicat-studio.itch.io/" target="_blank
    - label: GitHub
      icon: fab fa-fw fa-github
      url: &githubUrl https://github.com/12OI3" target="_blank
    - label: Steam
      icon: fab fa-fw fa-steam
      url: &steam https://steamcommunity.com/profiles/76561198395541214/" target="_blank
      
# Site Footer
footer:
  links:
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: *twitterUrl
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: *linkedinUrl
    - label: GitHub
      icon: fab fa-fw fa-github
      url: *githubUrl
    - label: Steam
      icon: fab fa-fw fa-steam
      url: *steam
    - label: Itch.io
      icon: fas fa-fw fa-gamepad
      url: *itch
    - label: Resume
      icon: fas fa-fw fa-user
      url: *resume
    - label: Email
      icon: fas fa-fw fa-envelope-square
      url: mailto:benbook90@gmail.com

atom_feed: # disable feed in footer
  hide: true

# Front Matter
defaults:
  # _work
  - scope:
      path: ""
      type: work
    values:
      layout: single
      author_profile: true
  # _article
  - scope:
      path: ""
      type: article
    values:
      layout: single
      author_profile: true
  # _devlog
  - scope:
      path: ""
      type: devlog
    values:
      layout: single
      author_profile: true

# Collection
collections:
  work:
    output: true
    permalink: /:collection/:path/
  article:
    output: true
    permalink: /:collection/:path/
  devlog:
    output: true
    permalink: /:collection/:path/